package nl.umcg.suresnp.pipeline;

import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;

public class IpcrToolsParameters {

    private static final Options OPTIONS;

    static {
        OPTIONS = new Options();
        Option option;

        option = Option.builder("T")
                .longOpt("tool")
                .hasArg(true)
                .desc("The tool to apply:\n" +
                        "* MergeWithBarcodes: Merge a IPCR (cutadapt) info file and the final alignment BAM file.\n" +
                        "                     BAM file MUST be sorted on query name (implemented this way for efficiency).\n" +
                        "-----------------------------------------------------------------------\n"+
                        "* AddAlleleInfo: Read a IPCR file generated by 'MergeBamWithBarcodes | sort -k 1,1 | uniq -c'\n" +
                        "                 and collapse the records so that barcodes appearing multiple times are\n" +
                        "                 collapsed on the record with the highest duplicate count.\n" +
                        "                 File MUST be sorted on barcode (for now). After collapsing add the\n" +
                        "                 variants located in each read based on the provided VCF")
                .argName("path/to/file")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("i")
                .longOpt("input-bam")
                .hasArg(true)
                .desc("Input bamfile SORTED ON QUERY NAME!!!!!")
                .argName("path/to/file")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("b")
                .longOpt("barcode-info")
                .hasArg(true)
                .desc("The file containing read names and barcodes")
                .argName("path/to/file")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("o")
                .longOpt("output")
                .hasArg(true)
                .desc("Output prefix")
                .argName("path/to/output")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("s")
                .longOpt("stdout")
                .desc("Pipe output to stdout instead of to a file. Will omit logging of warnings, info and debug.")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("g")
                .longOpt("input-genotype")
                .hasArg(true)
                .desc("Currently only supports VCF")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("p")
                .longOpt("input-ipcr-file")
                .hasArg(true)
                .desc("Input from MergeBamWithBarcodes. Sorted on barcode and first column must be duplicate count. " +
                        "See docs for format spec")
                .build();
        OPTIONS.addOption(option);

        option = Option.builder("h")
                .longOpt("help")
                .desc("Print usage")
                .build();
        OPTIONS.addOption(option);

    }

    public static Options getOptions(){
        return OPTIONS;
    }

    public static void printHelp() {
        HelpFormatter formatter = new HelpFormatter();
        formatter.setWidth(999);
        formatter.printHelp(" ", OPTIONS);
    }
}
