```{r}
setwd("../peakcalling")
source("../sure-snp_functions.r")

library(DESeq2)

count.matrix           <- fread("data/SuRE-SNP_CeD_x3_filtered.countMatrix", data.table = F)
rownames(count.matrix) <- count.matrix[,1]
count.matrix           <- count.matrix[,-1]
meta.data              <- read.table("data/SuRE-SNP_CeD_x3_filtered.samplesheet", stringsAsFactors = F, header=T)
row.names(meta.data)   <- meta.data$id

meta.data$ct_caco      <- as.factor(meta.data$ct_caco)
meta.data$ct_jurkat    <- as.factor(meta.data$ct_jurkat)
meta.data$ct_k562      <- as.factor(meta.data$ct_k562)

deseq.full             <- DESeqDataSetFromMatrix(countData = count.matrix,
                                     colData = meta.data[colnames(count.matrix),],
                                     design = ~stimulation)
```

# Merging technical replicates
```{r}
count.matrix.tmerged       <- data.frame(row.names=rownames(count.matrix))
for(celltype in unique(meta.data$stimulation)) {
  for (replicate in unique(meta.data[meta.data$stimulation == celltype,]$replicate)) {
    samples.to.sum <- rownames(meta.data)[meta.data$stimulation == celltype & meta.data$replicate == replicate] 
    new.id         <- gsub("_T.", "",samples.to.sum[1])
    count.matrix.tmerged[,new.id]   <- rowSums(count.matrix[, samples.to.sum])
  }
}

# Normalizing using VST
meta.data.tmerged           <- data.frame(matrix(unlist(strsplit(colnames(count.matrix.tmerged), split="_")),
                                      ncol=2,
                                      byrow=T),
                            row.names=colnames(count.matrix.tmerged))
colnames(meta.data.tmerged) <- c("celltype", "stimulation")
deseq.full.tmerged          <- DESeqDataSetFromMatrix(countData = count.matrix.tmerged,
                                     colData = meta.data.tmerged[colnames(count.matrix.tmerged),],
                                     design = ~stimulation)

results.tmerged        <- DESeq(deseq.full.tmerged)
pca.obj.tmerged        <- varianceStabilizingTransformation(results.tmerged)
x.tmerged              <- assay(pca.obj.tmerged)

write.table(x.tmerged, file="output/SuRE_CeD_consensus_peaks_x3_vst_normalized_count_matrix_technicals_merged.tsv", sep="\t", quote=F)
```

# PCA & correlations analysis of peaks: VST
```{r}
results <- DESeq(deseq.full)

# VST
pca.obj <- varianceStabilizingTransformation(results)
x       <- assay(pca.obj)

write.table(x, file="output/SuRE_CeD_consensus_peaks_x3_vst_normalized_count_matrix.tsv", sep="\t", quote=F)

# PCA plot
pdf(file="output/plots/pca_of_vst_normalized_peaks.pdf", width=6, height=5, paper="a4")
pc      <- prcomp(t(x))
pca.plot(pc,
         color=meta.data$stimulation,
         shape=meta.data$celltype, size = 4)
dev.off()

# Correlation heatmap
palette        <- sure.palette[c("celltype", "stimulation")]
names(palette) <- c("celltype", "simple_stimulation")
cor.m          <- cor(x)

pdf(file="output/plots/correlation_heatmap_of_vst_normalized_peaks.pdf", width=6, height=5, paper="a4")
simple.hm(cor.m, 
          range="absolute",
          annotation_row=meta.data[,c("celltype", "simple_stimulation")],
          annotation_colors=palette,
          min.value = 0.7,
          fontsize=8,
          cellwidth = 8.5,
          cellheight = 8.5,
          border_color=NA,
          treeheight_row=20,
          treeheight_col=20)
dev.off()
```

# PCA & correlations analysis of peaks: log2(TPM)
```{r}
# Verify from raw counts using TPM normalization
peak.lengths <- unlist(lapply(strsplit(gsub(".*\\:", "", rownames(count.matrix)), "-"),
                              function(x){return(as.numeric(x[2]) - as.numeric(x[1]))})) / 1000

norm.count.matrix <- count.matrix / peak.lengths
scale.factor      <- colSums(norm.count.matrix) / 1e6
norm.count.matrix <- t(apply(norm.count.matrix, 1, function(x){x / scale.factor}))

# PCA plot
pc      <- prcomp(t(log2(norm.count.matrix)))
pca.plot(pc,
         color=meta.data$stimulation,
         shape=meta.data$celltype, size = 4)

# Correlation plot
cor.m             <- cor(log2(norm.count.matrix))
simple.hm(cor.m, range="absolute",
          annotation_row=meta.data[,c("celltype", "simple_stimulation")],
          annotation_colors=palette)
```

# Stimulation: DE analysis
```{r}
jurkat.res   <- results(results, contrast=c("stimulation", "acd3/acd28", "j-baseline"), lfcThreshold = 1)
jurkat.res   <- as.data.frame(jurkat.res)

caco.res   <- results(results, contrast=c("stimulation", "iFNY", "c-baseline"), lfcThreshold = 1)
caco.res   <- as.data.frame(caco.res)
```

